version: '2'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    environment:
      http.host:              0.0.0.0
      xpack.security.enabled: 'false'
    ports:
      - 9222:9200
      - 9333:9300

  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_DB:       flambo
      POSTGRES_USER:     pg
      POSTGRES_PASSWORD: pg
    ports:
      - 5444:5432
