port: 7000

static:
  base_url: http://localhost:7000/static

jwt:
  secret: fl4mboO°

db:
  client:     pg
  debug:      false
  connection:
    host:     localhost
    port:     5432
    database: flambo
    user:     pg
    password: pg
  pool:
    min:      2
    max:      10

elastic:
  host:  localhost
  port:  9200
  log:   warning
  index: flambo

meetup:
  host: https://api.meetup.com