swagger: '2.0'
info:
  description: flambo API
  version: 1.0.0
  title: flambo
  contact: {}
host: 'localhost:8090'
basePath: /api/v1
produces:
  - application/json
paths:
  /groups:
    get:
      description: List groups
      summary: List groups
      tags:
        - groups
      responses:
        '200':
          description: Return the groups
          schema:
            type: object
            required:
              - items
              - page
              - hasNextPage
            properties:
              items:
                type: array
                items: &ref_0
                  type: object
                  required:
                    - id
                    - name
                  properties:
                    id:
                      type: string
                    name:
                      type: string
              page:
                description: the page number
                type: number
              hasNextPage:
                description: >-
                  Indicates if you can have more results or if you are on the
                  last page
                type: boolean
  '/groups/{id}':
    get:
      description: Get a group
      summary: Get a group
      tags:
        - groups
      parameters:
        - name: id
          in: path
          description: Group id
          required: true
          type: string
      responses:
        '200':
          description: Return the group
          schema: *ref_0
          examples:
            application/json:
              id: edd52c99-3280-44a2-ae5b-c6aa5ebc7e51
              name: flambo group
              slug: flambo-group
              description: The awesome flambo group
              created_at: '2017-05-16T01:48:41.596Z'
              updated_at: '2017-05-16T01:48:41.596Z'
              members_count: 5
              owner:
                id: 8ec88282-8c29-45c1-abe5-cbed11378794
                first_name: Raphaël
                last_name: Benitte
                avatar_url: 'http://flambo.io/static/user.png'
              viewer_is_owner: true
              picture_url: 'http://flambo.io/static/group.png'
              viewer_is_member: false
              viewer_is_administrator: false
  /collections:
    get:
      description: List collections
      summary: List collections
      tags:
        - collections
      responses:
        '200':
          description: Return the collections
          schema:
            type: object
            required:
              - items
              - page
              - hasNextPage
            properties:
              items:
                type: array
                items: &ref_1
                  type: object
                  required:
                    - id
                    - name
                  properties:
                    id:
                      type: string
                    name:
                      type: string
              page:
                description: the page number
                type: number
              hasNextPage:
                description: >-
                  Indicates if you can have more results or if you are on the
                  last page
                type: boolean
    post:
      description: Create a collection
      summary: Create a collection
      tags:
        - collections
      responses:
        '200':
          description: Return the created collection
          schema: *ref_1
  '/collections/{id}':
    get:
      description: Get a collection
      summary: Get a collection
      tags:
        - collections
      parameters:
        - name: id
          in: path
          description: Collection id
          required: true
          type: string
      responses:
        '200':
          description: Return the collection
          schema: *ref_1
  '/collections/{id}/feed':
    get:
      description: Get a collection feed
      summary: Get a collection feed
      tags:
        - collections
      parameters:
        - name: id
          in: path
          description: Collection id
          required: true
          type: string
      responses:
        '200':
          description: Return the collection feed
          schema: *ref_1
  '/collections/{id}/comments':
    get:
      description: Get a collection comments
      summary: Get a collection comments
      tags:
        - collections
      parameters:
        - name: id
          in: path
          description: Collection id
          required: true
          type: string
      responses:
        '200':
          description: Return the collection comments
          schema: *ref_1
  '/collections/{id}/subscribers':
    get:
      description: Get a collection subscribers
      summary: Get a collection subscribers
      tags:
        - collections
      parameters:
        - name: id
          in: path
          description: Collection id
          required: true
          type: string
      responses:
        '200':
          description: Return the collection subscribers
          schema: *ref_1
