swagger: '2.0'
info:
  description: flambo API
  version: 1.0.0
  title: flambo
  contact: {}
host: 'localhost:8090'
basePath: /api/v1
produces:
  - application/json
paths:
  /groups:
    get:
      description: List groups
      summary: List groups
      tags:
        - groups
      responses:
        '200':
          description: Return the groups
          schema:
            type: object
            required:
              - items
              - page
              - hasNextPage
            properties:
              items:
                type: array
                items: &ref_0
                  type: object
                  required:
                    - id
                    - name
                  properties:
                    id:
                      type: string
                    name:
                      type: string
              page:
                description: the page number
                type: number
              hasNextPage:
                description: >-
                  Indicates if you can have more results or if you are on the
                  last page
                type: boolean
  '/groups/{id}':
    get:
      description: Get a group
      summary: Get a group
      tags:
        - groups
      parameters:
        - name: id
          in: path
          description: Group id
          required: true
          type: string
      responses:
        '200':
          description: Return the group
          schema: *ref_0
  /collections:
    get:
      description: List collections
      summary: List collections
      tags:
        - collections
      responses:
        '200':
          description: Return the collections
          schema:
            type: object
            required:
              - items
              - page
              - hasNextPage
            properties:
              items:
                type: array
                items:
                  type: object
                  required:
                    - id
                    - name
                  properties:
                    id:
                      type: string
                    name:
                      type: string
              page:
                description: the page number
                type: number
              hasNextPage:
                description: >-
                  Indicates if you can have more results or if you are on the
                  last page
                type: boolean
